car_rental/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('add-car', views.add_car, name='add_car'),
    path('rent', views.rent, name='rent'),
    path('rent-details', views.rent_details, name='rent_details'),
    path('transactions', views.transactions, name='transactions'),
    path('reviews', views.reviews, name='reviews'),
    path('article', views.article, name='article'),
    path('login', views.log_in, name='log_in'),
    path('logout', views.log_out, name='log_out'),
    path('signup', views.signup, name='signup'),
    path('profile', views.profile_page, name='profile_page'),
    path('favourite-car', views.fav_car, name = 'favourite-car'),
    path('unfavourite-car', views.unfav_car, name = 'unfavourite-car'),
    path('api/search', views.search, name='search'),
    path('submit-review', views.submit_review, name = "submit_review"),
    path('delete-review', views.delete_review, name = "delete_review"),
    path('update-rating',views.update_rating,name='update_rating')

]

groupki6/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car_rental.urls')),
    path('', include('social_django.urls', namespace='social')),
]

car_rental/models.py
from django.db import models
from datetime import datetime, date
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from django.contrib.auth import get_user_model


rating_choice = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profileImage = models.URLField()

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()
    
class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
        
class Car(models.Model):
    carName = models.CharField(max_length=100)
    owner = models.CharField(max_length=50)
    category = models.ForeignKey(Category, on_delete = models.CASCADE)
    year = models.CharField(max_length=4)
    city = models.CharField(max_length=30)
    price = models.IntegerField()
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.carName
#Nambah model ini
class FavCar(models.Model):
    car = models.ForeignKey(Car, on_delete = models.CASCADE, primary_key = False)
    person = models.ForeignKey( User, on_delete = models.CASCADE, primary_key = False)
    

    def __str__(self):
        return self.car.carName

class ArticleModel(models.Model):
    title = models.CharField(max_length = 50)
    date =  models.DateField()
    content = models.CharField(max_length = 10000)
    rating = models.IntegerField(default=0)
    oldrating= models.IntegerField(default=0)
    totalrating=models.IntegerField(default=0)

    def __str__(self):
        return self.title

class ReviewModel(models.Model):
    title = models.CharField(max_length = 50)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    carChoice = Car.objects.all()
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    content = models.CharField(max_length = 10000)
    rating_choice = [('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')]
    rating = models.CharField(max_length=255, choices=rating_choice, default='NULL')
    startDate = models.DateField()
    endDate = models.DateField()
    dateCreated = models.DateTimeField('Created Time', auto_now_add=True, null=True)

    def __str__(self):
        return self.title

class TransactionModel(models.Model):
    username = models.CharField(max_length = 50)
    car = models.CharField(max_length = 50)
    date = models.DateTimeField('Created Time', auto_now_add=True, null=True)
    startDate = models.DateField()
    endDate = models.DateField()
    user = models.ForeignKey(User, on_delete = models.CASCADE)

    def __str__(self):
        return self.username

car_rental/forms.py
from django.forms import  TextInput, Select
from django import forms
from django.db import models
from django.forms import Select
from .models import Car, ReviewModel, TransactionModel, Profile, ArticleModel
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your forms here.
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    last_name = forms.CharField(max_length=30, required=True, help_text='Required.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    image = forms.URLField(required=True, help_text='Enter image url.')

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2', 'image')


class AddCar_Form(forms.ModelForm):
    class Meta:
        model = Car
        fields=['carName','owner',
        'category','year','price','city',
        'description']


class SearchCategory_Form(forms.ModelForm):
    class Meta:
        model = Car
        fields = [
            'category'
        ]
    
    def __init__(self, *args, **kwargs):
        super(SearchCategory_Form, self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Select a Car Type"
        # following line needed to refresh widget copy of choice list
        self.fields['category'].widget.choices = self.fields['category'].choices

class SearchResult_Form(forms.ModelForm):
    class Meta:
        model = Car
        fields = [
            'carName', 'owner', 'city', 'year', 'price' 
        ]

class DateInput(forms.DateInput):
    input_type = 'date'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = ReviewModel
        exclude = ('user',)
        fields = ['title', 'car', 'content', 'rating', 'startDate', 'endDate']
        widgets = {
            'title':forms.TextInput(attrs={'class':'form-control', 'id': 'title'}),
            'car':forms.Select(attrs={'class':'form-control', 'id': 'car'}),
            'content':forms.TextInput(attrs={'class':'form-control', 'id': 'content'}),
            'rating':forms.Select(attrs={'class':'form-control', 'id': 'rating'}),
            'startDate':DateInput(attrs={'id': 'startDate'}),
            'endDate':DateInput(attrs={'id': 'endDate'})
        }

class ArticleForm(forms.ModelForm):
    class Meta:
        model=ArticleModel
        fields= ['title','date','content']
        widgets={
            'title':forms.TextInput(attrs={'class':'form-control'}),
            'date':DateInput(),
            'content':forms.TextInput(attrs={'class':'form-control'})
            #'rating':forms.Select(attrs={'class':'form-control'})
        }        

class Transaction_Form(forms.ModelForm):
    class Meta:
        model = TransactionModel
        fields = ['username', 'car', 'startDate', 'endDate']
        widgets = {
            'username':forms.TextInput(attrs={'class':'form-control'}),
            'car':forms.TextInput(attrs={'class':'form-control'}),
            'startDate':DateInput(),
            'endDate':DateInput()
        }

car_rental/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from .forms import AddCar_Form, SearchCategory_Form, ReviewForm, SearchResult_Form, Transaction_Form, SignUpForm, ArticleForm
from .models import Car, ArticleModel, ReviewModel, TransactionModel, Profile, FavCar
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
from django.template import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.utils import dateparse
import json
import math

# Create your views here.
def homepage(request):
    return render(request, 'homepage.html')
    

def profile_page(request):
    if(request.user.is_authenticated):
        current_user = request.user
        favCarList = FavCar.objects.filter(person = current_user)
        reviewList = ReviewModel.objects.filter(user= current_user)
        transactionList  = TransactionModel.objects.filter(user = current_user)
        response = {'car' : favCarList, 'reviewList' : reviewList, 'transactions' : transactionList}
        return render(request, 'profile.html', response)
    return redirect('/login')

def log_in(request):
    
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        user_dict = {'username':username, 'password':password}
        if user is not None:
            login(request, user)
            return redirect('/')
        
        else:
            message = {'message':'Invalid username or password.'}
            return render(request, 'login.html', message)
    
    else :
        return render(request, 'login.html')

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST, request.FILES)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()
            user.profile.profileImage = form.cleaned_data.get('image')
            user.save()
            return redirect('/login')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form' : form})

def log_out(request):
    request.session.flush()
    logout(request)
    return redirect('/')

def add_car(request):
    if(request.user.is_authenticated):
        addCarForm = AddCar_Form()
        if (request.method=='POST'):
            addCarForm = AddCar_Form(request.POST)
            if(addCarForm.is_valid()):
                addCarForm.save()
                return HttpResponseRedirect('add-car')
            else:
                addCarForm = AddCar_Form()
        return render(request, 'add_car.html',{'form': addCarForm})
    return redirect('/login')

def rent(request):
    if(request.user.is_authenticated):
        searchForm = SearchCategory_Form()
        return render(request, 'rent.html', {'form' : searchForm})
    return redirect('/login')

def search(request):
    cars = 0
    if request.method == 'GET':
        if 'keyword' in request.GET and 'check' in request.GET:
            keyword = request.GET['keyword']
            if request.GET['check'] == 'category':
                if Car.objects.filter(category=keyword).exists():
                    cars = list(Car.objects.filter(category=keyword).values())
            elif request.GET['check'] == 'manual':
                if keyword.lower() == 'all':
                    cars = list(Car.objects.all().values())
                elif Car.objects.filter(carName__icontains=keyword).exists():
                    cars = list(Car.objects.filter(carName__icontains=keyword).values())
                elif keyword.isdigit():
                    if Car.objects.filter(price__lte=keyword).exists():
                        cars = list(Car.objects.filter(price__lte=keyword).values())   
    return JsonResponse({'cars': cars})

def rent_details(request):
    resultForm = SearchResult_Form()
    transactionForm = Transaction_Form()
    cars = Car.objects.all()
    if request.method == 'POST':
        if 'transaction' in request.POST:
            transactionForm = Transaction_Form(request.POST)
            transactionForm.car = request.POST.get('car')
            
            if transactionForm.is_valid():
                transaction = transactionForm.save(commit=False)
                transaction.user = request.user
                transactionForm.save()
                return HttpResponseRedirect('transactions')
        elif 'search' in request.POST:
            searchForm = SearchResult_Form(request.POST)
            if searchForm.is_valid():
                resultName = searchForm.cleaned_data['carName']
                resultOwner = searchForm.cleaned_data['owner']
                resultCity = searchForm.cleaned_data['city']
                resultYear = searchForm.cleaned_data['year']
                resultPrice = searchForm.cleaned_data['price']
                cars = cars.filter(carName = resultName, owner = resultOwner, city = resultCity, year = resultYear, price = resultPrice)
    return render(request, 'rent_details.html', {'cars' : cars, 'form' : transactionForm})

def fav_car(request):
    if request.method == "POST":
        carId = request.POST['id']
        car = Car.objects.get(id = carId)
        current_user = request.user
        if not FavCar.objects.filter(person = current_user, car = car).exists():
            new = FavCar()
            new.car = car
            new.person = current_user
            new.save()
    return HttpResponse('')

def unfav_car(request):
    if(request.user.is_authenticated):
        if request.method == "POST":
            fav = request.POST['fav']
            person  = request.user
            car = FavCar.objects.get(id = fav)
            car.delete()
            return redirect("/profile")
        person  = request.user
        favCarList = FavCar.objects.filter(person = person)
        response = {'car' : favCarList}
        return render(request, 'profile.html', response)
    return render(request, 'homepage.html')


def transactions(request):
    if(request.user.is_authenticated):
        response = TransactionModel.objects.all().order_by('-date')
        return render(request, 'transactions.html', {'transactions' : response})
    return redirect('/login')


def reviews(request):
    if(request.user.is_authenticated):
        form = ReviewForm()
        reviewList = ReviewModel.objects.all()
        response = {
            'form' : form,
            'reviewList' : reviewList
        }
        return render(request, 'reviews.html', response)
    return redirect('/login')


def article(request):
    if(request.user.is_authenticated):
        form= ArticleForm()
        if (request.method=='POST'):
            form = ArticleForm(request.POST)
            if(form.is_valid()):
                form.save()
                return HttpResponseRedirect('article')
        articleList = ArticleModel.objects.all()
        response = {
            'articleList' : articleList,
            'form': form
        }
        return render(request, 'article.html', response)
    return redirect('/login')



@csrf_exempt
def submit_review(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.user = request.user
            form.save()

            reviews = ReviewModel.objects.all()
            results=[]
            for review in reviews:
                createdCasted = str(dateparse.parse_datetime(str(review.dateCreated)).strftime('%B %d, %Y, %I:%M %p'))
                startCasted = str(review.startDate.strftime('%B %d, %Y'))
                endCasted = str(review.endDate.strftime('%B %d, %Y'))
                results.append({'id': review.id, 'title': review.title, 'user': review.user.username, 'car': review.car.carName, 'content': review.content, 'rating': review.rating, 'startDate': startCasted, 'endDate': endCasted, 'dateCreated': createdCasted})

    return JsonResponse({'newReviews': results})

@csrf_exempt
def delete_review(request):
    user = request.user
    if request.method == 'POST':
        if (user.username == request.POST['reviewUser']):
            review = ReviewModel.objects.get(id = request.POST['reviewId'])
            review.delete()

            reviews = ReviewModel.objects.all()
            results=[]
            for review in reviews:
                createdCasted = str(dateparse.parse_datetime(str(review.dateCreated)).strftime('%B %d, %Y, %I:%M %p'))
                startCasted = str(review.startDate.strftime('%B %d, %Y'))
                endCasted = str(review.endDate.strftime('%B %d, %Y'))
                results.append({'id': review.id, 'title': review.title, 'user': review.user.username, 'car': review.car.carName, 'content': review.content, 'rating': review.rating, 'startDate': startCasted, 'endDate': endCasted, 'dateCreated': createdCasted})

    return JsonResponse({'newReviews': results})
    
def update_rating(request):

    if request.method == 'GET':
        titlestring = request.GET['title']
        ratingstring= request.GET['rating_value']
        article = ArticleModel.objects.get(title=titlestring) 
        article.rating += 1
        temp=article.totalrating
        calculation= ((temp+int(ratingstring))/article.rating)
        article.totalrating+= int(ratingstring)
        article.oldrating=math.floor(calculation)

        article.save()
        return HttpResponse(article.oldrating) 
    return HttpResponse("Request method is not a GET")
     
    

car_rental/templates/rent.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Rent</title>
{% endblock %}

{% block content %}
    <div class="row flex-grow-1">
        <div class="col-lg-12 bgstyle" style="padding: 0;">
        
            <center>
                <h1 class="titleText">Want to rent a car?</h1>
            </center>
            <div class="container" style="width: 50%;"> 
                <form method="POST">
                    {% csrf_token %} 
                    <label  for="category"><h3>Search By Category</h3></label> <br>
                    {{ form.category }}
                    <br><br>
                    <div class="text-right">
                        <button type="submit" class="about" id="categorySearch">Search</button>
                    </div>
                </form>
                <div class="text-center">
                    <h3>---OR---</h3>
                </div>
                <form method="POST">
                    {% csrf_token %} 
                    <label  for="category"><h3>Search By Name/Price</h3></label> <br>
                    <input type="text" class="form-control" id="manualSearchBox" placeholder="E.g. 'Alphard' or '50000' or 'All'"/>
                    <br>
                    <div class="text-right">
                        <button type="submit" class="about" id="manualSearch">Search</button>
                    </div>
                </form>
            </div>
            <br>
            <div class="d-flex justify-content-center">
                <div id="resultCarousel" class="carousel slide mb-5" data-ride="carousel">
                    <ol class="carousel-indicators">
                      <li data-target="#resultCarousel" data-slide-to="0" class="active"></li>
                    </ol>
                    <div class="carousel-inner" style="height: 100%;">
                      <div class="carousel-item active" style="height: 100%;">
                        <div class="d-flex align-items-center justify-content-center" style="height: 100%;">
                            <h3>Your search results will be displayed here</h3>
                        </div>
                      </div>
                    </div>
                    <a class="carousel-control-prev" href="#resultCarousel" role="button" data-slide="prev">
                      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                      <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#resultCarousel" role="button" data-slide="next">
                      <span class="carousel-control-next-icon" aria-hidden="true"></span>
                      <span class="sr-only">Next</span>
                    </a>
                </div>
            </div>

            
        </div>
    </div>
{% endblock %}

{% block initialize %}
    <script type = "text/javascript">
        $(document).on('click','.button-item',function(e){
            e.preventDefault();
            var $this = $(this);
            var $id = $this.attr('id').split('-')[1];

            
            $.ajax({
                type:'POST',
                url:'/favourite-car',
                data: {
                    id : $id,

                    csrfmiddlewaretoken : $('input[name=csrfmiddlewaretoken]').val(),
                },
                success:function(){
                    alert("Favourited!");

                }

            });
        });

        $(document).on('click', '#manualSearch', function(e){
            e.preventDefault();
            var keyword = $('#manualSearchBox').val();
            $.ajax({
                url: "{% url 'search' %}",
                data: {keyword:keyword, check:'manual'},
                dataType: "json",
                type: "GET",
                success: function(response){
                    found(response);
                },
                error: function(){
                    notFound();
                }
            });
        });

        $(document).on('click', '#categorySearch', function(e){
            e.preventDefault();
            var keyword = $("#id_category option:selected").val();
            $.ajax({
                url: "{% url 'search' %}",
                data: {keyword:keyword, check:'category'},
                dataType: "json",
                type: "GET",
                success: function(response){
                    found(response);
                },
                error: function(){
                    notFound();
                }
            });
        });

        function found(response){
            if(response.cars == 0){
                notFound();
            }else{
                var carouselIndicatorResult = '<li data-target="#resultCarousel" data-slide-to="0" class="active"></li>'
                                            + '<li data-target="#resultCarousel" data-slide-to="1" class="active"></li>';
                var carouselInnerResult = '<div class="carousel-item active" style="height: 100%;">'
                                            + '<div class="d-flex align-items-center justify-content-center" style="height: 100%;">'
                                                + '<h3>Here are your search results</h3>'
                                            + '</div>'
                                        + '</div>'
                                        + '<div class="carousel-item" style="height: 100%;">'
                                            + "<div class='p-5 mx-4'>"
                                                + "<h6 id='carName-" + response.cars[0].id + "'>Car name: " + response.cars[0].carName + "</h6>"
                                                + "<h6 id='owner-" + response.cars[0].id + "'>Owner: " + response.cars[0].owner + "</h6>"
                                                + "<h6 id='city-" + response.cars[0].id + "'>City: " + response.cars[0].city + "</h6>"
                                                + "<h6 id='year-" + response.cars[0].id + "''>Year: " + response.cars[0].year + "</h6>"
                                                + "<h6 id='price-" + response.cars[0].id + "'>Price (per day): " + response.cars[0].price + "</h6>"
                                                + "<h6 id='desc-" + response.cars[0].id + "'>Description: " + response.cars[0].description + "</h6>"
                                            + "</div>"
                                            + "<center><button class='button-item' id='btn-" + response.cars[0].id + "'>❤️️</button></center>" +"<br>"
                                            + "<form method='POST' action=\"{% url 'rent_details' %}\">"
                                                + '{% csrf_token %}'
                                                + "<input name='carName' type='hidden' value='" + response.cars[0].carName + "'>"
                                                + "<input name='owner' type='hidden' value='" + response.cars[0].owner + "'>"
                                                + "<input name='city' type='hidden' value='" + response.cars[0].city + "'>"
                                                + "<input name='year' type='hidden' value='" + response.cars[0].year + "'>"
                                                + "<input name='price' type='hidden' value='" + response.cars[0].price + "'>"
                                                + "<input name='description' type='hidden' value='" + response.cars[0].description + "'>"
                                            + "<div class='text-center mb-5'>"
                                                + "<input class='submit_button' type='Submit' name='search' value='Rent'>"
                                            + "</div>"
                                            + "</form>"
                                        + '</div>';
                for(var i = 1;i < response.cars.length;i++){
                    carouselIndicatorResult += '<li data-target="#resultCarousel" data-slide-to="' + (i+1) + '" class="active"></li>';
                    carouselInnerResult += "<div class='carousel-item' style='height: 100%;''>" 
                                            + "<div class='p-5 mx-4'>"
                                                + "<h6 id='carName-" + response.cars[i].id + "'>Car name: " + response.cars[i].carName + "</h6>"
                                                + "<h6 id='owner-" + response.cars[i].id + "'>Owner: " + response.cars[i].owner + "</h6>"
                                                + "<h6 id='city-" + response.cars[i].id + "'>City: " + response.cars[i].city + "</h6>"
                                                + "<h6 id='year-" + response.cars[i].id + "''>Year: " + response.cars[i].year + "</h6>"
                                                + "<h6 id='price-" + response.cars[i].id + "'>Price (per day): " + response.cars[i].price + "</h6>"
                                                + "<h6 id='desc-" + response.cars[i].id + "'>Description: " + response.cars[i].description + "</h6>"
                                            + "</div>"
                                            + "<center><button class='button-item' id='btn-" + response.cars[i].id + "'>❤️️</button></center>" + "<br>"
                                            + "<form method='POST' action=\"{% url 'rent_details' %}\">"
                                                + '{% csrf_token %}'
                                                + "<input name='carName' type='hidden' value='" + response.cars[i].carName + "'>"
                                                + "<input name='owner' type='hidden' value='" + response.cars[i].owner + "'>"
                                                + "<input name='city' type='hidden' value='" + response.cars[i].city + "'>"
                                                + "<input name='year' type='hidden' value='" + response.cars[i].year + "'>"
                                                + "<input name='price' type='hidden' value='" + response.cars[i].price + "'>"
                                                + "<input name='description' type='hidden' value='" + response.cars[i].description + "'>"
                                            + "<div class='text-center mb-5'>"
                                                + "<input class='submit_button' type='Submit' name='search' value='Rent'>"
                                            + "</div>"
                                            + "</form>"
                                        + "</div>"                        
                }
                $('.carousel-indicators').empty();
                $('.carousel-indicators').append(carouselIndicatorResult);
                $('.carousel-inner').empty();
                $('.carousel-inner').append(carouselInnerResult);
            }
        };

        function notFound(){
            var carouselIndicatorResult = '<li data-target="#resultCarousel" data-slide-to="0" class="active"></li>';
            var carouselInnerResult = '<div class="carousel-item active" style="height: 100%;">'
                                        + '<div class="d-flex align-items-center justify-content-center" style="height: 100%;">'
                                            + '<h3>No car matches the keyword</h3>'
                                        + '</div>'
                                    + '</div>';
            $('.carousel-indicators').empty();
            $('.carousel-indicators').append(carouselIndicatorResult);
            $('.carousel-inner').empty();
            $('.carousel-inner').append(carouselInnerResult);
        };
    </script>
{% endblock %}

car_rental/templates/rent_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Rent</title>
{% endblock %}

{% block content %}
<div class="row flex-grow-1">
    <div class="col-lg-12 bgstyle" style="padding: 0;">
        <center>
            <h1 class="titleText">Want to rent a car?</h1>
        </center>
        <div class="card bg-white text-dark" style="width: 80%; margin-bottom:5%; margin-left:10%; margin-right:5%; margin-top:2.5% ">
            <div class="card-body">
                {% for c in cars %}
                <h6 class="card-title">Car name: {{ c.carName }}</h6>
                <h6 class="card-title">Owner: {{ c.owner }}</h6>
                <h6 class="card-title">City: {{ c.city }}</h6>
                <h6 class="card-title">Year: {{ c.year }}</h6>
                <h6 class="card-title">Price: {{ c.price }}</h6>
                {% endfor %}
            </div>
        </div>
        <div class="container" style="width: 50%;"> 
            <form method="POST" action="">
                {% csrf_token %} 
                {% for c in cars %}
                <input type="hidden" name="car" id="id_car" value="{{ c.carName }}">
                {% endfor %}
                <label for="username">Name </label> <br>
                {{ form.username }}
                <label  for="startDate">Start Date </label> <br>
                {{ form.startDate }}
                <br>
                <label  for="endDate">End Date </label> <br>
                {{ form.endDate }}
                <br><br>
                <div class="text-right pr-4">
                    <input class="submit_button" type="Submit" name="transaction" value="Rent" style="display: inline-block;">
                </div>
                <br>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block initialize %}
    <script type="text/javascript">
    </script>
{% endblock %}